INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('alamasma@ymail.com', 'Orange Juice', 7, 1, 20, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('arefinshawon@gmail.com', 'Chicken Cheese Delight', 10, 1, 120, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('arefinshawon@gmail.com', 'Chicken Cheese Delight', 11, 1, 120, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('arefinshawon@gmail.com', 'Club Sandwich', 8, 1, 140, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('arefinshawon@gmail.com', 'Cold Coffee', 9, 1, 60, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Burger Large', 16, 1, 250, 'PROCESSED', '2018-11-30');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Burger Large', 23, 1, 250, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Club Sandwich', 21, 1, 140, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Club Sandwich', 22, 1, 140, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Egg Menu', 30, 1, 250, 'PROCESSED', '2018-12-02');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('asifabrar@gmail.com', 'Noodles', 15, 1, 100, 'PROCESSED', '2018-11-30');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', '7-UP', 28, 1, 20, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', 'Club Sandwich', 3, 2, 280, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', 'Club Sandwich', 29, 1, 140, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', 'Coca Cola', 2, 4, 80, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', 'Coca Cola', 27, 1, 20, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('masterben@gmail.com', 'Orange Juice', 1, 1, 20, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', '7-UP', 32, 4, 80, 'PROCESSED', '2018-12-02');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Biriani', 4, 2, 300, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Biriani', 13, 1, 150, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Coca Cola', 12, 1, 20, 'PROCESSED', '2018-11-29');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Coca Cola', 18, 4, 80, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Cold Coffee', 6, 1, 60, 'PROCESSED', '2018-11-28');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Orange Juice', 19, 1, 20, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Orange Juice', 20, 1, 20, 'PROCESSED', '2018-12-01');
INSERT INTO Canteen.order_info (EMAIL, FNAME, ORDER_NO, QUANTITY, PRICE_TOTAL, FLAG, ORDER_DATE) VALUES ('sohanuddin@gmail.com', 'Regular Fries', 31, 1, 70, 'PROCESSED', '2018-12-02');